updates:
  - directory: /
    open-pull-requests-limit: 16
    package-ecosystem: github-actions
    schedule:
      interval: daily
    versioning-strategy: increase
  - directory: /
    open-pull-requests-limit: 16
    package-ecosystem: npm
    schedule:
      interval: daily
    versioning-strategy: increase
version: 2
