author: kei-g
branding:
  color: blue
  icon: download
description: >
  Checkouts an arbitrary repository,
  and calculates the digest of specified files except under '.git' directory in it.
name: Checkout a repository with digest
inputs:
  algorithm:
    default: sha256
    description: >
      The hash algorithm applied to calculate the digest,
      either 'md5' or 'sha1' or 'sha256' or 'sha512'.
  encoding:
    default: hex
    description: >
      The style for output, either 'base64' or 'base64url' or 'hex'.
  fetch-depth:
    default: '1'
    description: >
      Number of commits to fetch. 0 indicates all history for all branches and tags.
  paths-ignore:
    description: >
      Paths to be excluded to calculate the digest.
      `paths-ignore` priors to `paths-to-hash` invariably.


      '.git/**' is always excluded.
    required: false
  paths-to-hash:
    description: >
      Paths to be included to calculate the digest.
      `paths-ignore` priors to `paths-to-hash` invariably.


      '.git/**' is always excluded.
    required: false
  persist-credentials:
    default: 'true'
    description: >
      Whether to configure the token or SSH key with the local git config.
  ref:
    description: >
      The branch, tag or SHA to checkout.
      When checking out the repository that triggered a workflow,
      this defaults to the reference or SHA for that event.
      Otherwise, uses the default branch.
  repository:
    default: ${{ github.repository }}
    description: 'Repository name with owner.'
  ssh-key:
    description: >
      SSH key used to fetch the repository.
      The SSH key is configured with the local git config,
      which enables your scripts to run authenticated git commands.
      The post-job step removes the SSH key.


      We recommend using a service account with the least permissions necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
  ssh-known-hosts:
    description: >
      Known hosts in addition to the user and global host key database.
      The public SSH keys for a host may be obtained using the utility `ssh-keyscan`.
      For example, `ssh-keyscan github.com`.
      The public key for github.com is always implicitly added.
  ssh-strict:
    default: 'true'
    description: >
      Whether to perform strict host key checking.
      When true, adds the options `StrictHostKeyChecking=yes` and `CheckHostIP=no` to the SSH command line.
      Use the input `ssh-known-hosts` to configure additional hosts.
  submodules:
    default: 'false'
    description: >
      Whether to checkout submodules: `true` to checkout submodules or `recursive` to recursively checkout submodules.
      When the `ssh-key` input is not provided,
      SSH URLs beginning with `git@github.com:` are converted to HTTPS.
  token:
    default: ${{ github.token }}
    description: >
      Personal access token (PAT) used to fetch the repository.
      The PAT is configured with the local git config,
      which enables your scripts to run authenticated git commands.
      The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
outputs:
  digest:
    description: >
      The calculated digest.
    value: ${{ steps.calculate.outputs.digest }}
runs:
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        persist-credentials: ${{ inputs.persist-credentials }}
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}
        ssh-key: ${{ inputs.ssh-key }}
        ssh-known-hosts: ${{ inputs.ssh-known-hosts }}
        ssh-strict: ${{ inputs.ssh-strict }}
        submodules: ${{ inputs.submodules }}
        token: ${{ inputs.token }}
    - id: calculate
      name: Calculates the digest of their data to be hashed
      uses: kei-g/github/checkout/digest@main
      with:
        algorithm: ${{ inputs.algorithm }}
        encoding: ${{ inputs.encoding }}
        paths-ignore: ${{ inputs.paths-ignore }}
        paths-to-hash: ${{ inputs.paths-to-hash }}
  using: composite
