author: kei-g
branding:
  color: blue
  icon: cpu
description: >
  Calculates the digest of specified files except under '.git' directory.
name: Calculates the digest
inputs:
  algorithm:
    default: sha256
    description: >
      The hash algorithm applied to calculate the digest,
      either 'md5' or 'sha1' or 'sha256' or 'sha512'.
  encoding:
    default: hex
    description: >
      The style for output, either 'base64' or 'base64url' or 'hex'.
  paths-ignore:
    description: >
      Paths to be excluded to calculate the digest.
      `paths-ignore` priors to `paths-to-hash` invariably.


      '.git/**' is always excluded.
    required: false
  paths-to-hash:
    description: >
      Paths to be included to calculate the digest.
      `paths-ignore` priors to `paths-to-hash` invariably.


      '.git/**' is always excluded.
    required: false
runs:
  main: ../../dist/digest.mjs
  using: node20
